/*
 * Exact-build battle-roster extractor owned by twitchstat.c4p.
 *
 * A click is only the snapshot trigger. The payload contains all twelve visual slots and the
 * logical-game geometry needed by a future Twitch overlay. Unit text is generated by a temporary
 * hidden CEncLayoutUnit and copied from the same named controls the player sees after RMB. Calls go
 * through verified game-EXE entry points, so whichever mss32/toolset hooks are currently installed
 * participate naturally; this plugin contains no mss32.dll RVA or private Lua ABI.
 */

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <Windows.h>

#include <algorithm>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

namespace {

constexpr std::uintptr_t kRussobitManagerDataRva = 0x437CE4;
constexpr std::uintptr_t kRussobitBatViewerVftableRva = 0x2F4294;
constexpr std::uintptr_t kRussobitEncLayoutUnitVftableRva = 0x2E7F7C;
constexpr DWORD kRussobitExeSize = 4187648;
constexpr DWORD kRussobitCustomIconExeSize = 4214272;

constexpr unsigned kBatViewerOffset = 24;
constexpr unsigned kViewerDataOffset = 28;
constexpr unsigned kViewerData2Offset = 32;
constexpr unsigned kOpenEncyclopediaOffset = 60;
constexpr unsigned kBattleMsgDataOffset = 48;
constexpr unsigned kDialogInterfAreaOffset = 4140;
constexpr unsigned kObjectMapOffset = 5376;
constexpr unsigned kViewerUnitIdOffset = 0xF9C;
constexpr unsigned kBatUnitGroupOffsets[] = {4996, 5016, 5000, 5020};
constexpr int kEmptyId = 0x003F0000;

// Russobit/MNS EXE entry points. Active mss32 detours remain in this call path.
constexpr std::uintptr_t kGameAllocate = 0x509530;
constexpr std::uintptr_t kEncParamCtor = 0x5744DF;
constexpr std::uintptr_t kEncParamDtor = 0x57456B;
constexpr std::uintptr_t kEncParamSetStatus = 0x574314;
constexpr std::uintptr_t kEncParamSetData = 0x574342;
constexpr std::uintptr_t kEncParamAddBattleInfo = 0x63B1A1;
constexpr std::uintptr_t kBatEncyclopediaCtor = 0x65A7A0;
constexpr std::uintptr_t kFindTextBox = 0x50BB0F;
constexpr std::uintptr_t kFindListBox = 0x50BACF;
constexpr std::uintptr_t kGetBattleUnitInfo = 0x622EF5;
constexpr std::uintptr_t kGetEncyclopediaPlayerId = 0x5EBDCE;
constexpr std::uintptr_t kGetShatteredArmor = 0x62332C;
constexpr std::uintptr_t kGetFortificationArmor = 0x623391;

struct NativeRect { int left, top, right, bottom; };
struct NativePoint { int x, y; };

struct NativeListNode
{
    NativeListNode* next;
    NativeListNode* previous;
    void* data;
};

struct NativeList
{
    std::uint32_t length;
    NativeListNode* head;
    int unknown;
    void* allocator;
};

struct NativeString
{
    std::uint32_t length;
    std::uint32_t allocated;
    char* text;
    void* allocator;
};

struct NativeStringVector
{
    NativeString* begin;
    NativeString* end;
    NativeString* allocatedEnd;
    void* allocator;
};

struct NativeInterface
{
    void** vftable;
    void* interfaceData;
};

struct NativeEncLayout
{
    void** vftable;
    void* interfaceData;
    void* dialog;
    void* data;
};

struct NativeBatEncyclopedia
{
    void** vftable;
    void* interfaceData;
    int unknown;
    char* data;
};

// The fourth CBatEncyclopediaInterf constructor argument is not a nullable parent pointer. It is
// the address of an 8-byte ref-counted callback handle. The native constructor copies both words
// unconditionally through 0x6578E0 -> 0x53C557, so even an empty callback must have valid storage.
struct NativeCallbackHandle
{
    void* controlBlock;
    void* callback;
};

struct NativeUiControl
{
    void** vftable;
    void* interfaceData;
    char* data;
};

struct NativeEncParamIdPlayer { std::uint8_t bytes[16]; };
struct SlotRect { short left, top, right, bottom; };

constexpr SlotRect kSlots[12] = {
    {  7,  87,  77, 172}, { 87,  87, 157, 172},
    {  7, 193,  77, 278}, { 87, 193, 157, 278},
    {  7, 299,  77, 384}, { 87, 299, 157, 384},
    {833,  87, 903, 172}, {913,  87, 983, 172},
    {833, 193, 903, 278}, {913, 193, 983, 278},
    {833, 299, 903, 384}, {913, 299, 983, 384},
};

static_assert(sizeof(void*) == 4, "Twitch Stat targets the 32-bit game process");
static_assert(sizeof(NativeListNode) == 12, "Russobit list-node layout drift");
static_assert(sizeof(NativeList) == 16, "Russobit list layout drift");
static_assert(sizeof(NativeString) == 16, "Russobit string layout drift");
static_assert(sizeof(NativeEncLayout) == 16, "Russobit encyclopedia layout drift");
static_assert(sizeof(NativeBatEncyclopedia) == 16,
              "Russobit battle encyclopedia wrapper drift");
static_assert(sizeof(NativeCallbackHandle) == 8,
              "Russobit callback-handle layout drift");

struct BattleContext
{
    char* viewer;
    void* batViewer;
    char* data;
    char* data2;
    char* battle;
    void* objectMap;
    NativeRect area;
};

struct NativeEncyclopedia
{
    char name[1024];
    char description[8192];
    char stats[8192];
    char statsExtra[8192];
    char leader[4096];
    char attack[16384];
    char upgrade[4096];
    int effectCount;
    char effects[32][4096];
};

struct UnitPublic
{
    int internalId;
    std::string name;
    std::string description;
    std::string stats;
    std::string statsExtra;
    std::string leader;
    std::string attack;
    std::string upgrade;
    std::vector<std::string> effects;
};

struct SlotSnapshot { int unitIndex; };

bool g_cleanupFault = false; // UI-thread only; a structural mismatch disables extraction safely
char g_lastDiagnostic[320] = "not-called"; // UI-thread only; consumed immediately by unitinfo.cpp
const char* g_hiddenStage = "not-called";
const char* g_hiddenExceptionStage = "none";
DWORD g_hiddenExceptionCode = 0;
const void* g_hiddenExceptionAddress = nullptr;

LONG captureHiddenException(EXCEPTION_POINTERS* information)
{
    g_hiddenExceptionStage = g_hiddenStage;
    g_hiddenExceptionCode = 0;
    g_hiddenExceptionAddress = nullptr;
    if (information && information->ExceptionRecord) {
        g_hiddenExceptionCode = information->ExceptionRecord->ExceptionCode;
        g_hiddenExceptionAddress = information->ExceptionRecord->ExceptionAddress;
    }
    return EXCEPTION_EXECUTE_HANDLER;
}

void setDiagnostic(const char* format, ...)
{
    va_list arguments;
    va_start(arguments, format);
    _vsnprintf_s(g_lastDiagnostic, sizeof(g_lastDiagnostic), _TRUNCATE, format, arguments);
    va_end(arguments);
    g_lastDiagnostic[sizeof(g_lastDiagnostic) - 1] = 0;
}

bool isExactRussobitExecutable()
{
    char path[MAX_PATH] = {};
    if (!GetModuleFileNameA(nullptr, path, static_cast<DWORD>(sizeof(path))))
        return false;
    WIN32_FILE_ATTRIBUTE_DATA attributes = {};
    if (!GetFileAttributesExA(path, GetFileExInfoStandard, &attributes) ||
        attributes.nFileSizeHigh != 0)
        return false;
    return attributes.nFileSizeLow == kRussobitExeSize ||
           attributes.nFileSizeLow == kRussobitCustomIconExeSize;
}

void* findWideBattleViewer()
{
    if (!isExactRussobitExecutable()) {
        setDiagnostic("unsupported-executable-size");
        return nullptr;
    }

    void* result = nullptr;
    __try {
        const std::uintptr_t imageBase =
            reinterpret_cast<std::uintptr_t>(GetModuleHandleW(nullptr));
        if (!imageBase) {
            setDiagnostic("missing-executable-image-base");
            return nullptr;
        }

        char* manager = *reinterpret_cast<char**>(imageBase + kRussobitManagerDataRva);
        char* managerData = manager ? *reinterpret_cast<char**>(manager + 8) : nullptr;
        NativeList* interfaces = managerData
            ? reinterpret_cast<NativeList*>(managerData + 24) : nullptr;
        if (!interfaces || !interfaces->head || interfaces->length == 0 ||
            interfaces->length > 64) {
            setDiagnostic("invalid-interface-list");
            return nullptr;
        }

        NativeListNode* const head = interfaces->head;
        NativeListNode* node = head->next;
        const void* const expectedVftable =
            reinterpret_cast<const void*>(imageBase + kRussobitBatViewerVftableRva);
        std::uint32_t visited = 0;
        std::uint32_t vftableMatches = 0;
        while (node && node != head && visited++ < interfaces->length) {
            char* candidate = static_cast<char*>(node->data);
            if (candidate &&
                *reinterpret_cast<void**>(candidate + kBatViewerOffset) == expectedVftable) {
                ++vftableMatches;
                char* data = *reinterpret_cast<char**>(candidate + kViewerDataOffset);
                char* data2 = *reinterpret_cast<char**>(candidate + kViewerData2Offset);
                const char* dialogName = data2 ? *reinterpret_cast<const char**>(data2) : nullptr;
                const NativeRect* area = data
                    ? reinterpret_cast<const NativeRect*>(data + kDialogInterfAreaOffset) : nullptr;
                void* objectMap = data
                    ? *reinterpret_cast<void**>(data + kObjectMapOffset) : nullptr;
                if (dialogName && strcmp(dialogName, "DLG_BATTLE_B") == 0 && area && objectMap &&
                    area->right - area->left == 990 && area->bottom - area->top == 600) {
                    result = candidate + kBatViewerOffset;
                    setDiagnostic("battle-viewer-found list=%lu visited=%lu",
                                  static_cast<unsigned long>(interfaces->length),
                                  static_cast<unsigned long>(visited));
                    break;
                }
            }
            node = node->next;
        }
        if (!result) {
            setDiagnostic("battle-viewer-not-found list=%lu visited=%lu vtable-matches=%lu",
                          static_cast<unsigned long>(interfaces->length),
                          static_cast<unsigned long>(visited),
                          static_cast<unsigned long>(vftableMatches));
        }
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        result = nullptr;
        setDiagnostic("battle-viewer-scan-exception");
    }
    return result;
}

bool captureBattleContext(void* batViewer, BattleContext* out)
{
    if (!batViewer || !out)
        return false;
    memset(out, 0, sizeof(*out));
    __try {
        out->batViewer = batViewer;
        out->viewer = reinterpret_cast<char*>(batViewer) - kBatViewerOffset;
        out->data = *reinterpret_cast<char**>(out->viewer + kViewerDataOffset);
        out->data2 = *reinterpret_cast<char**>(out->viewer + kViewerData2Offset);
        if (!out->data || !out->data2)
            return false;
        out->battle = out->data + kBattleMsgDataOffset;
        out->objectMap = *reinterpret_cast<void**>(out->data + kObjectMapOffset);
        if (!out->objectMap)
            return false;
        out->area = *reinterpret_cast<const NativeRect*>(
            out->data + kDialogInterfAreaOffset);
        return out->area.right - out->area.left == 990 &&
               out->area.bottom - out->area.top == 600;
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        memset(out, 0, sizeof(*out));
        return false;
    }
}

bool hasOpenUnitEncyclopedia(const BattleContext& context)
{
    bool found = false;
    __try {
        // Native RMB owns a CBatEncyclopediaInterf through CBattleViewerInterfData2+60; its
        // CEncLayoutUnit is nested below that wrapper rather than attached directly to the viewer.
        if (context.data2 &&
            *reinterpret_cast<void* const*>(context.data2 + kOpenEncyclopediaOffset))
            return true;

        const std::uintptr_t imageBase =
            reinterpret_cast<std::uintptr_t>(GetModuleHandleW(nullptr));
        NativeInterface* parent = reinterpret_cast<NativeInterface*>(context.viewer);
        if (!imageBase || !parent || !parent->vftable)
            return true; // fail closed: do not add a child when the parent cannot be inspected

        using GetChildsCount = int(__thiscall*)(const void*);
        using GetChild = NativeInterface*(__thiscall*)(void*, const int*);
        const int count = reinterpret_cast<GetChildsCount>(parent->vftable[20])(parent);
        if (count < 0 || count > 256)
            return true;

        const void* const encyclopediaVftable = reinterpret_cast<const void*>(
            imageBase + kRussobitEncLayoutUnitVftableRva);
        for (int i = 0; i < count; ++i) {
            NativeInterface* child =
                reinterpret_cast<GetChild>(parent->vftable[21])(parent, &i);
            if (child && child->vftable == encyclopediaVftable) {
                found = true;
                break;
            }
        }
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        found = true;
    }
    return found;
}

int displayedUnitAt(const BattleContext& context, int localX, int localY)
{
    int result = 0;
    __try {
        const NativePoint point = {localX, localY};
        using GetSelectedUnitId = int*(__thiscall*)(const void*, int*, const NativePoint*);
        for (unsigned groupOffset : kBatUnitGroupOffsets) {
            void* group = *reinterpret_cast<void**>(context.data + groupOffset);
            if (!group)
                continue;
            int candidate = kEmptyId;
            reinterpret_cast<GetSelectedUnitId>(0x64E04C)(group, &candidate, &point);
            if (candidate && candidate != kEmptyId) {
                result = candidate;
                break;
            }
        }
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        result = 0;
    }
    return result;
}

int slotAtPoint(int localX, int localY)
{
    for (int i = 0; i < 12; ++i) {
        const SlotRect& rect = kSlots[i];
        if (localX >= rect.left && localX < rect.right &&
            localY >= rect.top && localY < rect.bottom)
            return i;
    }
    return -1;
}

bool copyNativeString(const NativeString* value, char* destination, size_t capacity)
{
    if (!destination || capacity == 0)
        return false;
    destination[0] = 0;
    if (!value || value->length == 0)
        return true;
    if (!value->text || value->length > 1024 * 1024)
        return false;
    const size_t count = std::min<size_t>(value->length, capacity - 1);
    memcpy(destination, value->text, count);
    destination[count] = 0;
    return true;
}

bool copyTextBox(void* dialog, const char* controlName, char* destination, size_t capacity)
{
    if (!destination || !capacity)
        return false;
    destination[0] = 0;
    if (!dialog)
        return false;
    using FindTextBox = NativeUiControl*(__stdcall*)(void*, const char*);
    NativeUiControl* box = reinterpret_cast<FindTextBox>(kFindTextBox)(dialog, controlName);
    if (!box || !box->data)
        return true; // optional controls differ between layouts/mods
    return copyNativeString(reinterpret_cast<const NativeString*>(box->data + 20),
                            destination, capacity);
}

bool tryCopyEffectsVector(const NativeStringVector* vector, int expected,
                          NativeEncyclopedia* output)
{
    bool result = false;
    __try {
        if (!vector)
            return false;
        const std::uintptr_t begin = reinterpret_cast<std::uintptr_t>(vector->begin);
        const std::uintptr_t end = reinterpret_cast<std::uintptr_t>(vector->end);
        const std::uintptr_t allocatedEnd =
            reinterpret_cast<std::uintptr_t>(vector->allocatedEnd);
        if (!begin || end < begin || allocatedEnd < end ||
            (end - begin) % sizeof(NativeString) != 0)
            return false;
        const size_t count = (end - begin) / sizeof(NativeString);
        if (count == 0)
            return expected == 0;
        if (count > 32 || count != static_cast<size_t>(expected))
            return false;
        for (size_t i = 0; i < count; ++i) {
            const NativeString& item = vector->begin[i];
            if (item.length == 0 || item.length >= sizeof(output->effects[0]) || !item.text ||
                !copyNativeString(&item, output->effects[i], sizeof(output->effects[i])))
                return false;
        }
        output->effectCount = static_cast<int>(count);
        result = true;
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        result = false;
    }
    return result;
}

bool captureVisibleEffects(NativeEncLayout* layout, NativeEncyclopedia* output)
{
    if (!layout || !layout->dialog || !layout->data || !output)
        return false;
    output->effectCount = 0;

    int total = 0;
    __try {
        using FindListBox = NativeUiControl*(__stdcall*)(void*, const char*);
        NativeUiControl* list =
            reinterpret_cast<FindListBox>(kFindListBox)(layout->dialog, "LBOX_MODIFIERS");
        if (!list)
            return true;
        if (!list->data)
            return false;
        total = *reinterpret_cast<int*>(list->data + 52);
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        return false;
    }
    if (total < 0)
        return false;
    if (total == 0)
        return true;
    if (total > 32)
        return false;

    // No mss32 code address is used. The current toolset's append-only CEncLayoutUnitData extension
    // places its modifier-text Vector<String> at +84 (inside its verified 108-byte allocation).
    // Do not scan arbitrary trailing memory: an unknown extension must fail closed instead.
    char* data = static_cast<char*>(layout->data);
    const NativeStringVector* texts =
        reinterpret_cast<const NativeStringVector*>(data + 84);
    if (tryCopyEffectsVector(texts, total, output))
        return true;
    // The hook uses one synthetic "None" row when there are no actual modifier strings.
    return total == 1 && tryCopyEffectsVector(texts, 0, output);
}

bool captureHiddenEncyclopedia(const BattleContext& context, int unitId,
                               NativeEncyclopedia* output)
{
    g_hiddenStage = "arguments";
    g_hiddenExceptionStage = "none";
    g_hiddenExceptionCode = 0;
    g_hiddenExceptionAddress = nullptr;
    if (!unitId || !output)
        return false;
    memset(output, 0, sizeof(*output));

    NativeEncParamIdPlayer param = {};
    NativeCallbackHandle emptyCallback = {};
    bool paramConstructed = false;
    NativeBatEncyclopedia* wrapper = nullptr;
    bool wrapperAllocated = false;
    bool wrapperCtorEntered = false;
    bool wrapperConstructed = false;
    NativeEncLayout* layout = nullptr;
    bool captured = false;

    __try {
        g_hiddenStage = "unit-info";
        using GetUnitInfo = char*(__stdcall*)(const void*, const int*);
        char* unitInfo = reinterpret_cast<GetUnitInfo>(kGetBattleUnitInfo)(
            context.battle, &unitId);
        if (!unitInfo)
            __leave;
        using GetEncyclopediaPlayerId = const int*(__stdcall*)(const int*, const void*);
        const int* playerId = reinterpret_cast<GetEncyclopediaPlayerId>(
            kGetEncyclopediaPlayerId)(
                reinterpret_cast<const int*>(context.data + kViewerUnitIdOffset),
                context.objectMap);
        if (!playerId)
            __leave;

        g_hiddenStage = "parameter-constructor";
        using ParamCtor = NativeEncParamIdPlayer*(__thiscall*)(
            NativeEncParamIdPlayer*, const int*, const int*, void*);
        reinterpret_cast<ParamCtor>(kEncParamCtor)(&param, &unitId, playerId, nullptr);
        paramConstructed = true;

        // Mirror CBattleViewerInterf::showEncyclopedia exactly. Without IsInBattle the layout
        // follows its out-of-battle object lookup path, which is invalid for temporary/summoned
        // battle units. Shattered and fortification armor are also visible encyclopedia values.
        g_hiddenStage = "parameter-battle-status";
        using SetStatus = void(__thiscall*)(NativeEncParamIdPlayer*, int, bool);
        reinterpret_cast<SetStatus>(kEncParamSetStatus)(&param, 0x800, true);

        g_hiddenStage = "parameter-battle-values";
        using GetBattleValue = int(__thiscall*)(const void*, const int*);
        using SetData = void(__thiscall*)(NativeEncParamIdPlayer*, int, int);
        const int shatteredArmor = reinterpret_cast<GetBattleValue>(kGetShatteredArmor)(
            context.battle, &unitId);
        const int fortificationArmor =
            reinterpret_cast<GetBattleValue>(kGetFortificationArmor)(context.battle, &unitId);
        reinterpret_cast<SetData>(kEncParamSetData)(&param, 1, shatteredArmor);
        reinterpret_cast<SetData>(kEncParamSetData)(&param, 2, fortificationArmor);

        g_hiddenStage = "add-battle-info";
        using AddBattleInfo = void(__stdcall*)(
            NativeEncParamIdPlayer*, const int*, const void*);
        reinterpret_cast<AddBattleInfo>(kEncParamAddBattleInfo)(
            &param, &unitId, context.battle);

        g_hiddenStage = "wrapper-allocation";
        using Allocate = void*(__cdecl*)(int);
        wrapper = static_cast<NativeBatEncyclopedia*>(
            reinterpret_cast<Allocate>(kGameAllocate)(sizeof(NativeBatEncyclopedia)));
        if (!wrapper)
            __leave;
        wrapperAllocated = true;

        // Construct the same native owner used by RMB, but never publish it at viewer->data2+60.
        // With no manager-list publication it cannot draw or receive input. Sticky mode means the
        // temporary wrapper does not need a close callback, but the constructor still requires the
        // address of a structurally valid (empty) ref-counted callback handle.
        g_hiddenStage = "wrapper-constructor";
        using WrapperCtor = NativeBatEncyclopedia*(__thiscall*)(
            NativeBatEncyclopedia*, const NativeEncParamIdPlayer*, const void*,
            const NativeCallbackHandle*, bool);
        wrapperCtorEntered = true;
        NativeBatEncyclopedia* constructed = reinterpret_cast<WrapperCtor>(
            kBatEncyclopediaCtor)(wrapper, &param, context.objectMap, &emptyCallback, true);
        if (!constructed)
            __leave;
        wrapper = constructed;
        wrapperConstructed = true;

        g_hiddenStage = "layout-fetch";
        if (!wrapper->data)
            __leave;
        layout = *reinterpret_cast<NativeEncLayout**>(wrapper->data + 24);
        if (!layout)
            __leave;

        g_hiddenStage = "visible-controls";
        if (!copyTextBox(layout->dialog, "TXT_UNIT_NAME", output->name,
                         sizeof(output->name)) ||
            !copyTextBox(layout->dialog, "TXT_UNIT_INFO", output->description,
                         sizeof(output->description)) ||
            !copyTextBox(layout->dialog, "TXT_STATS", output->stats,
                         sizeof(output->stats)) ||
            !copyTextBox(layout->dialog, "TXT_STATS_2", output->statsExtra,
                         sizeof(output->statsExtra)) ||
            !copyTextBox(layout->dialog, "TXT_LEADER_INFO", output->leader,
                         sizeof(output->leader)) ||
            !copyTextBox(layout->dialog, "TXT_ATTACK_INFO", output->attack,
                         sizeof(output->attack)) ||
            !copyTextBox(layout->dialog, "TXT_NEED_UPGRADE", output->upgrade,
                         sizeof(output->upgrade)) ||
            !captureVisibleEffects(layout, output))
            __leave;

        g_hiddenStage = "visible-text-empty";
        captured = output->name[0] != 0 || output->description[0] != 0 ||
                   output->stats[0] != 0 || output->attack[0] != 0;
        if (captured)
            g_hiddenStage = "captured";
    } __except (captureHiddenException(GetExceptionInformation())) {
        captured = false;
        g_hiddenStage = g_hiddenExceptionStage;
    }

    if (wrapperAllocated && wrapper) {
        bool destroyed = false;
        if (wrapperConstructed) {
            __try {
                g_hiddenStage = "wrapper-cleanup";
                if (wrapper->vftable && wrapper->vftable[0]) {
                    using WrapperDtor = void(__thiscall*)(NativeBatEncyclopedia*, unsigned char);
                    reinterpret_cast<WrapperDtor>(wrapper->vftable[0])(wrapper, 1);
                    destroyed = true;
                    wrapper = nullptr;
                }
            } __except (captureHiddenException(GetExceptionInformation())) {
                destroyed = false;
                g_hiddenStage = g_hiddenExceptionStage;
            }
        }
        if (!destroyed) {
            captured = false;
            g_cleanupFault = true;
            if (!g_hiddenExceptionCode)
                g_hiddenStage = wrapperCtorEntered ? "partial-wrapper-leaked"
                                                   : "wrapper-allocation";
            // The wrapper is detached from both the battle tree and the manager list. On a partial
            // constructor failure it is safer to quarantine one unreachable allocation than call
            // a destructor on an object whose construction boundary is unknown.
        }
    }
    if (paramConstructed) {
        __try {
            using ParamDtor = void(__thiscall*)(NativeEncParamIdPlayer*);
            reinterpret_cast<ParamDtor>(kEncParamDtor)(&param);
        } __except (EXCEPTION_EXECUTE_HANDLER) {
            captured = false;
            g_hiddenStage = "parameter-destructor";
        }
    }
    if (captured)
        g_hiddenStage = "success";
    return captured;
}

UINT configuredAnsiCodePage()
{
    char iniPath[MAX_PATH] = {};
    if (!GetModuleFileNameA(nullptr, iniPath, static_cast<DWORD>(sizeof(iniPath))))
        return GetACP();
    char* slash = strrchr(iniPath, '\\');
    if (slash)
        strcpy_s(slash + 1, static_cast<size_t>(iniPath + sizeof(iniPath) - slash - 1),
                 "Disciple.ini");
    else
        strcpy_s(iniPath, "Disciple.ini");

    const LCID systemLocale = GetUserDefaultLCID();
    const LCID configured = static_cast<LCID>(
        GetPrivateProfileIntA("Wrapper", "Locale", static_cast<int>(systemLocale), iniPath));
    char text[16] = {};
    unsigned codePage = 0;
    if (GetLocaleInfoA(configured, LOCALE_IDEFAULTANSICODEPAGE, text,
                       static_cast<int>(sizeof(text))) &&
        sscanf_s(text, "%u", &codePage) == 1 && codePage)
        return codePage;
    if (configured != systemLocale &&
        GetLocaleInfoA(systemLocale, LOCALE_IDEFAULTANSICODEPAGE, text,
                       static_cast<int>(sizeof(text))) &&
        sscanf_s(text, "%u", &codePage) == 1 && codePage)
        return codePage;
    return GetACP();
}

std::string stripGameMarkup(const char* source)
{
    if (!source)
        return {};
    std::string result;
    result.reserve(strlen(source));
    for (size_t i = 0; source[i];) {
        const unsigned char ch = static_cast<unsigned char>(source[i]);
        if (ch != '\\') {
            result.push_back(static_cast<char>(ch));
            ++i;
            continue;
        }

        const char next = source[i + 1];
        if (next == 'n' || next == 'N') {
            result.push_back('\n');
            i += 2;
            continue;
        }
        if (next == 'r' || next == 'R') {
            i += 2;
            continue;
        }
        if (next == 't' || next == 'T') {
            result.push_back('\t');
            i += 2;
            continue;
        }
        if (next == '\\') {
            result.push_back('\\');
            i += 2;
            continue;
        }

        size_t end = i + 1;
        while (source[end] && source[end] != ';' && end - i <= 48)
            ++end;
        if (source[end] == ';') {
            i = end + 1;
            continue;
        }
        result.push_back('\\');
        ++i;
    }

    std::string normalized;
    normalized.reserve(result.size());
    bool lineStart = true;
    int consecutiveNewlines = 0;
    for (char ch : result) {
        if (ch == '\r')
            continue;
        if (ch == '\n') {
            while (!normalized.empty() &&
                   (normalized.back() == ' ' || normalized.back() == '\t'))
                normalized.pop_back();
            if (consecutiveNewlines < 2)
                normalized.push_back('\n');
            ++consecutiveNewlines;
            lineStart = true;
            continue;
        }
        if (lineStart && (ch == ' ' || ch == '\t'))
            continue;
        normalized.push_back(ch);
        lineStart = false;
        consecutiveNewlines = 0;
    }
    while (!normalized.empty() &&
           (normalized.back() == ' ' || normalized.back() == '\t' ||
            normalized.back() == '\n'))
        normalized.pop_back();
    return normalized;
}

std::string gameTextToUtf8(const char* source)
{
    const std::string plain = stripGameMarkup(source);
    if (plain.empty())
        return {};
    UINT codePage = configuredAnsiCodePage();
    if (!codePage)
        codePage = GetACP();
    int wideLength = MultiByteToWideChar(
        codePage, 0, plain.c_str(), static_cast<int>(plain.size()), nullptr, 0);
    if (wideLength <= 0 && codePage != 1251) {
        codePage = 1251;
        wideLength = MultiByteToWideChar(
            codePage, 0, plain.c_str(), static_cast<int>(plain.size()), nullptr, 0);
    }
    if (wideLength <= 0)
        return {};
    std::wstring wide(static_cast<size_t>(wideLength), L'\0');
    if (!MultiByteToWideChar(codePage, 0, plain.c_str(), static_cast<int>(plain.size()),
                             &wide[0], wideLength))
        return {};
    const int utf8Length = WideCharToMultiByte(
        CP_UTF8, 0, wide.data(), wideLength, nullptr, 0, nullptr, nullptr);
    if (utf8Length <= 0)
        return {};
    std::string utf8(static_cast<size_t>(utf8Length), '\0');
    WideCharToMultiByte(CP_UTF8, 0, wide.data(), wideLength,
                        &utf8[0], utf8Length, nullptr, nullptr);
    return utf8;
}

UnitPublic makePublicUnit(int unitId, const NativeEncyclopedia& source)
{
    UnitPublic result = {};
    result.internalId = unitId; // extraction-only dedupe key; never serialized
    result.name = gameTextToUtf8(source.name);
    result.description = gameTextToUtf8(source.description);
    result.stats = gameTextToUtf8(source.stats);
    result.statsExtra = gameTextToUtf8(source.statsExtra);
    result.leader = gameTextToUtf8(source.leader);
    result.attack = gameTextToUtf8(source.attack);
    result.upgrade = gameTextToUtf8(source.upgrade);
    for (int i = 0; i < source.effectCount; ++i) {
        std::string text = gameTextToUtf8(source.effects[i]);
        if (!text.empty())
            result.effects.push_back(std::move(text));
    }
    return result;
}

void appendEscaped(std::string& out, const std::string& value)
{
    static const char hex[] = "0123456789abcdef";
    out.push_back('"');
    for (unsigned char ch : value) {
        switch (ch) {
        case '"': out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\b': out += "\\b"; break;
        case '\f': out += "\\f"; break;
        case '\n': out += "\\n"; break;
        case '\r': out += "\\r"; break;
        case '\t': out += "\\t"; break;
        default:
            if (ch < 0x20) {
                out += "\\u00";
                out.push_back(hex[(ch >> 4) & 0xF]);
                out.push_back(hex[ch & 0xF]);
            } else {
                out.push_back(static_cast<char>(ch));
            }
            break;
        }
    }
    out.push_back('"');
}

void appendStringField(std::string& out, const char* indent, const char* key,
                       const std::string& value, bool comma = true)
{
    out += indent;
    appendEscaped(out, key);
    out += ": ";
    appendEscaped(out, value);
    out += comma ? ",\n" : "\n";
}

void appendIntField(std::string& out, const char* indent, const char* key,
                    long long value, bool comma = true)
{
    char number[64];
    sprintf_s(number, "%lld", value);
    out += indent;
    appendEscaped(out, key);
    out += ": ";
    out += number;
    out += comma ? ",\n" : "\n";
}

void appendBoolField(std::string& out, const char* indent, const char* key,
                     bool value, bool comma = true)
{
    out += indent;
    appendEscaped(out, key);
    out += value ? ": true" : ": false";
    out += comma ? ",\n" : "\n";
}

void appendBounds(std::string& out, const NativeRect& bounds)
{
    char number[64];
    out += "{\"left\": ";
    sprintf_s(number, "%d", bounds.left);
    out += number;
    out += ", \"top\": ";
    sprintf_s(number, "%d", bounds.top);
    out += number;
    out += ", \"right\": ";
    sprintf_s(number, "%d", bounds.right);
    out += number;
    out += ", \"bottom\": ";
    sprintf_s(number, "%d", bounds.bottom);
    out += number;
    out += "}";
}

void appendOptionalSection(std::string& json, const char* key, const std::string& value,
                           bool comma)
{
    json += "      ";
    appendEscaped(json, key);
    json += ": ";
    if (value.empty())
        json += "null";
    else
        appendEscaped(json, value);
    json += comma ? ",\n" : "\n";
}

std::string buildJson(const BattleContext& context, int frameWidth, int frameHeight,
                      int selectedSlot, const SlotSnapshot slots[12],
                      const std::vector<UnitPublic>& units)
{
    std::string json;
    json.reserve(4096 + units.size() * 8192);
    json += "{\n";
    appendStringField(json, "  ", "schema", "c4dll.battle-roster");
    appendIntField(json, "  ", "schema_version", 1);
    appendStringField(json, "  ", "event", "battle.snapshot");
    json += "  \"coordinate_space\": {\n";
    appendStringField(json, "    ", "name", "logical_game_surface");
    appendIntField(json, "    ", "width", frameWidth);
    appendIntField(json, "    ", "height", frameHeight);
    appendStringField(json, "    ", "bounds_semantics",
                      "left_top_inclusive_right_bottom_exclusive", false);
    json += "  },\n";
    json += "  \"battle\": {\n";
    appendStringField(json, "    ", "dialog", "DLG_BATTLE_B");
    json += "    \"bounds\": ";
    appendBounds(json, context.area);
    json += "\n  },\n";
    json += "  \"selection\": {\n";
    appendStringField(json, "    ", "side", selectedSlot < 6 ? "left" : "right");
    appendIntField(json, "    ", "index", selectedSlot % 6, false);
    json += "  },\n";
    json += "  \"slots\": [\n";
    for (int i = 0; i < 12; ++i) {
        const bool left = i < 6;
        const SlotRect& local = kSlots[i];
        const NativeRect absolute = {
            context.area.left + local.left,
            context.area.top + local.top,
            context.area.left + local.right,
            context.area.top + local.bottom,
        };
        json += "    {\n";
        char id[16];
        sprintf_s(id, "%s-%d", left ? "left" : "right", i % 6 + 1);
        appendStringField(json, "      ", "id", id);
        appendStringField(json, "      ", "side", left ? "left" : "right");
        appendIntField(json, "      ", "index", i % 6);
        json += "      \"bounds\": ";
        appendBounds(json, absolute);
        json += ",\n";
        appendBoolField(json, "      ", "occupied", slots[i].unitIndex >= 0);
        json += "      \"unit_index\": ";
        if (slots[i].unitIndex >= 0) {
            char number[16];
            sprintf_s(number, "%d", slots[i].unitIndex);
            json += number;
        } else {
            json += "null";
        }
        json += "\n    }";
        json += i < 11 ? ",\n" : "\n";
    }
    json += "  ],\n";
    json += "  \"units\": [\n";
    for (size_t i = 0; i < units.size(); ++i) {
        const UnitPublic& unit = units[i];
        json += "    {\n";
        appendIntField(json, "      ", "index", static_cast<long long>(i));
        appendStringField(json, "      ", "name", unit.name);
        appendOptionalSection(json, "description", unit.description, true);
        appendOptionalSection(json, "stats", unit.stats, true);
        appendOptionalSection(json, "stats_extra", unit.statsExtra, true);
        appendOptionalSection(json, "leader", unit.leader, true);
        appendOptionalSection(json, "attack", unit.attack, true);
        appendOptionalSection(json, "upgrade", unit.upgrade, true);
        json += "      \"effects\": [";
        for (size_t effect = 0; effect < unit.effects.size(); ++effect) {
            if (effect)
                json += ", ";
            appendEscaped(json, unit.effects[effect]);
        }
        json += "]\n    }";
        json += i + 1 < units.size() ? ",\n" : "\n";
    }
    json += "  ]\n";
    json += "}\n";
    return json;
}

} // namespace

// A cleanup mismatch is quarantined for the rest of that battle. The old viewer owns any retained
// offscreen child and destroys it on teardown; the next battle starts with a fresh UI tree.
extern "C" void battleunitinfo_reset_battle(void)
{
    g_cleanupFault = false;
    setDiagnostic("battle-reset");
}

extern "C" const char* battleunitinfo_last_diagnostic(void)
{
    return g_lastDiagnostic;
}

// Coordinates and frame size use the same logical-game space as C4P_Canvas/c4p_mouse.
extern "C" int battleunitinfo_get_json_at(int x, int y, int frameWidth, int frameHeight,
                                            char* utf8Json, std::uint32_t capacity,
                                            std::uint32_t* required)
{
    if (required)
        *required = 0;
    if (g_cleanupFault) {
        setDiagnostic("cleanup-quarantine");
        return 0;
    }
    if (frameWidth <= 0 || frameHeight <= 0) {
        setDiagnostic("invalid-frame-size %dx%d", frameWidth, frameHeight);
        return 0;
    }

    void* batViewer = findWideBattleViewer();
    BattleContext context = {};
    if (!batViewer)
        return 0; // findWideBattleViewer supplied the precise reason
    if (!captureBattleContext(batViewer, &context)) {
        setDiagnostic("battle-context-invalid");
        return 0;
    }

    // A genuine RMB encyclopedia and this temporary one may share mod-owned state. Never create a
    // second CEncLayoutUnit while the player is viewing the first; leave the click entirely to the
    // game and resume automatically after that child is closed.
    if (hasOpenUnitEncyclopedia(context)) {
        setDiagnostic("native-encyclopedia-open");
        return 0;
    }

    const int localX = x - context.area.left;
    const int localY = y - context.area.top;
    const int hintedSlot = slotAtPoint(localX, localY);
    // The game's own WM handler subtracts dialogInterfArea.left/top before calling
    // CBatUnitGroup2::getSelectedUnitId. The group's base point and portrait offsets are therefore
    // DLG_BATTLE_B-local, just like kSlots. This native hit-test is authoritative: a large unit is
    // one 150x85 portrait, while kSlots describes two 70x85 logical cells separated by a 10px seam.
    const int clickedUnitId = displayedUnitAt(context, localX, localY);
    if (!clickedUnitId) {
        if (hintedSlot < 0) {
            setDiagnostic("outside-unit click=%d,%d local=%d,%d battle=%d,%d,%d,%d",
                          x, y, localX, localY, context.area.left, context.area.top,
                          context.area.right, context.area.bottom);
        } else {
            setDiagnostic("slot-hit-empty slot=%d click=%d,%d local=%d,%d",
                          hintedSlot, x, y, localX, localY);
        }
        return 0;
    }

    SlotSnapshot slots[12] = {};
    for (SlotSnapshot& slot : slots)
        slot.unitIndex = -1;
    int uniqueIds[12] = {};
    int uniqueCount = 0;

    for (int i = 0; i < 12; ++i) {
        const SlotRect& rect = kSlots[i];
        const int unitId = displayedUnitAt(context,
                                           (rect.left + rect.right) / 2,
                                           (rect.top + rect.bottom) / 2);
        if (!unitId)
            continue;
        int unitIndex = -1;
        for (int known = 0; known < uniqueCount; ++known) {
            if (uniqueIds[known] == unitId) {
                unitIndex = known;
                break;
            }
        }
        if (unitIndex < 0) {
            if (uniqueCount >= 12)
            {
                setDiagnostic("roster-overflow");
                return 0;
            }
            unitIndex = uniqueCount;
            uniqueIds[uniqueCount++] = unitId;
        }
        slots[i].unitIndex = unitIndex;
    }

    // Preserve the exact logical cell when the point is inside one. In the seam of a native large
    // portrait, choose the nearest of its two matching logical cells. A static rectangle is never
    // allowed to veto a unit that the game's own hit-test accepted.
    int selectedSlot = -1;
    if (hintedSlot >= 0 && slots[hintedSlot].unitIndex >= 0 &&
        uniqueIds[slots[hintedSlot].unitIndex] == clickedUnitId) {
        selectedSlot = hintedSlot;
    } else {
        int bestDistance = 0x7fffffff;
        for (int i = 0; i < 12; ++i) {
            if (slots[i].unitIndex < 0 ||
                uniqueIds[slots[i].unitIndex] != clickedUnitId)
                continue;
            const SlotRect& rect = kSlots[i];
            const int dx = localX < rect.left ? rect.left - localX
                         : localX >= rect.right ? localX - (rect.right - 1) : 0;
            const int dy = localY < rect.top ? rect.top - localY
                         : localY >= rect.bottom ? localY - (rect.bottom - 1) : 0;
            const int distance = dx * dx + dy * dy;
            if (distance < bestDistance) {
                bestDistance = distance;
                selectedSlot = i;
            }
        }
    }

    if (selectedSlot < 0 || uniqueCount == 0) {
        setDiagnostic("clicked-unit-not-in-roster hint=%d unit=%08X unique=%d",
                      hintedSlot, static_cast<unsigned>(clickedUnitId), uniqueCount);
        return 0;
    }

    try {
        std::vector<UnitPublic> units;
        units.reserve(static_cast<size_t>(uniqueCount));
        // Keep the ~180 KiB native text scratch area off the game's already-deep UI-thread stack.
        std::unique_ptr<NativeEncyclopedia> encyclopedia(new NativeEncyclopedia());
        for (int i = 0; i < uniqueCount; ++i) {
            if (!captureHiddenEncyclopedia(context, uniqueIds[i], encyclopedia.get())) {
                setDiagnostic("hidden-capture-failed unit-index=%d unit-id=%08X stage=%s "
                              "seh=%08lX@%p quarantine=%d",
                              i, static_cast<unsigned>(uniqueIds[i]), g_hiddenStage,
                              static_cast<unsigned long>(g_hiddenExceptionCode),
                              g_hiddenExceptionAddress, g_cleanupFault ? 1 : 0);
                return 0; // do not publish a mixed/partial battle snapshot
            }
            units.push_back(makePublicUnit(uniqueIds[i], *encyclopedia));
        }

        const std::string json = buildJson(
            context, frameWidth, frameHeight, selectedSlot, slots, units);
        const size_t bytes = json.size() + 1;
        if (required)
            *required = bytes > UINT32_MAX ? UINT32_MAX : static_cast<std::uint32_t>(bytes);
        if (!utf8Json || capacity < bytes) {
            setDiagnostic("buffer-too-small capacity=%lu required=%lu",
                          static_cast<unsigned long>(capacity),
                          static_cast<unsigned long>(bytes));
            return -1;
        }
        memcpy(utf8Json, json.c_str(), bytes);
        setDiagnostic("success slot=%d hint=%d remapped=%d units=%d bytes=%lu",
                      selectedSlot, hintedSlot, selectedSlot != hintedSlot ? 1 : 0,
                      uniqueCount, static_cast<unsigned long>(bytes));
        return 1;
    } catch (...) {
        setDiagnostic("cpp-exception");
        return 0;
    }
}
